openapi: 3.0.0

info:
  version: "0.2"
  title: COVID-19 Testing Channel Availability Service
  description: |
    ## Overview
    Use this API to get status information on channels available to deliver COVID-19 tests.
    
    ## Authorisation
    This API is [application-restricted](https://digital.nhs.uk/developer/security-and-authorisation#application-restricted-apis),
    meaning the calling application must be authorised to use it.
    
    TBC details on how to do it.
    
    ## Environments and testing
    | Environment       | Base URL                                                               |
    | ----------------- | ---------------------------------------------------------------------- |
    | Integration test  | `https://int.api.service.nhs.uk/covid-19-testing-channel-availability` |
    | Production        | `https://api.service.nhs.uk/covid-19-testing-channel-availability`     |
   
    ### Integration testing
    Our [integration test environment](https://digital.nhs.uk/developer/testing#integration-testing) is for formal integration testing.

    You can try out the sandbox using our Postman collection:
    [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/e5ab94b5fa4f711dda2c)

  contact:
    name: "API Management Support"
    email: "api.management@nhs.net"
  
tags:
  - name: Channel Availablity Service
    
servers:
- url: "https://int.api.service.nhs.uk/covid-19-testing-channel-availability"
  description: "Integration Test Environment"
paths:
  /status:
    get:
      operationId: getStatus
      tags:
      - Channel Availability
      summary: Returns the status information on channels available to delivery COVID-19 tests.
      parameters:
      - in: header
        name: X-Correlation-ID
        required: false
        description: Identifier used to track requests across systems. Should be output in any logs
        schema:
          type: string
          format: uuid
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChannelAvailabilityStatusResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorised"
        "403":
          $ref: "#/components/responses/Forbidden"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    ChannelAvailabilityStatusResponse:
      type: object
      required:
        - keyworker
        - citizen
      properties:
        keyworker:
          allOf:
            - $ref: '#/components/schemas/ParticipantAvailability'
          description: Availablity of channels for key workers
        citizen:
          allOf:
            - $ref: '#/components/schemas/ParticipantAvailability'
          description: Availablity of channels for citizens
    ParticipantAvailability:
      type: object
      required:
        - home
        - testCentre
      properties:
        home:
          type: boolean
          description: Availability of the home channel for the participant grouping
        testCentre:
          $ref: '#/components/schemas/TestCentreAvailability'
    TestCentreAvailability:
      type: object
      required:
        - regions
        - subRegions
      properties:
        available:
          type: boolean
          description: Deprecated value to set availabilty across all nations
        regions:
          $ref: '#/components/schemas/RegionAvailability'
        subRegions:
          type: array
          items:
            $ref: '#/components/schemas/SubRegionAvailability'
    RegionAvailability:
      type: object
      required:
        - GB-ENG
        - GB-WLS
        - GB-SCT
        - GB-NIR
      properties:
        GB-ENG:
          type: boolean
          description: The availability of testing centres within England
        GB-WLS:
          type: boolean
          description: The availability of testing centres within Wales
        GB-SCT:
          type: boolean
          description: The availability of testing centres within Scotland
        GB-NIR:
          type: boolean
          description: The availability of testing centres within Northern Ireland
    SubRegionAvailability:
      type: object
      required:
        - id
        - description
        - available
        - region
        - availabilityLevel
      properties:
        id:
          type: string
          format: uuid
          description: The id of the sub-region
        description:
          type: string
          description: The sub-region description in human-readable format
          example: Yorkshire and the North-East
        available:
          type: boolean
          description: The availability of testing centres within the sub-region
        region:
          type: string
          enum:
            - GB-ENG
            - GB-WLS
            - GB-SCT
            - GB-NIR
          description: The region to which the sub-region belogs.
        availabilityLevel:
          type: string
          description: The level of appointment availability
          example: Good availablity
    Error:
      type: object
      required:
        - statusCode
        - message
      properties:
        statusCode:
          type: integer
          description: Status code of the error
        message:
          type: string
          description: Description of the error
  responses:
    BadRequest:
      description: The request was badly formed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified subject was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorised:
      description: Unauthorised. The client lacks authentication credentials for this request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden. The authenticated client is not allowed to perform the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
